@main
struct WakeStateTests {
    static func main() {
        var lockedFirst = WakeState()
        lockedFirst.pause(.locked, wasClosing: true)
        lockedFirst.pause(.systemSleep, wasClosing: false)
        lockedFirst.pause(.displaySleep, wasClosing: false)
        lockedFirst.resume(.systemSleep)
        lockedFirst.resume(.displaySleep)
        precondition(lockedFirst.isSuspended && !lockedFirst.consumeOpening(at: 45, startAngle: 90), "wake must wait for unlock")
        lockedFirst.resume(.locked)
        precondition(lockedFirst.consumeOpening(at: 45, startAngle: 90), "lock-before-sleep must preserve the opening")
        lockedFirst.resume(.systemSleep)
        lockedFirst.resume(.displaySleep)
        precondition(!lockedFirst.consumeOpening(at: 45, startAngle: 90), "duplicate wake must not replay the opening")

        var sleepingFirst = WakeState()
        sleepingFirst.pause(.systemSleep, wasClosing: true)
        sleepingFirst.pause(.displaySleep, wasClosing: false)
        sleepingFirst.pause(.locked, wasClosing: false)
        sleepingFirst.resume(.locked)
        sleepingFirst.resume(.systemSleep)
        precondition(!sleepingFirst.consumeOpening(at: 45, startAngle: 90), "unlock must wait for the display to wake")
        sleepingFirst.pause(.inactiveSession, wasClosing: false)
        sleepingFirst.resume(.displaySleep)
        precondition(!sleepingFirst.consumeOpening(at: 45, startAngle: 90), "opening must stay hidden in another user's session")
        sleepingFirst.resume(.inactiveSession)
        precondition(sleepingFirst.consumeOpening(at: 45, startAngle: 90), "active unlocked desktop must receive one opening")

        var idle = WakeState()
        idle.pause(.systemSleep, wasClosing: false)
        idle.resume(.systemSleep)
        precondition(!idle.consumeOpening(at: 45, startAngle: 90), "idle sleep with an open lid must not animate")
        idle.pause(.locked, wasClosing: true)
        idle.resume(.locked)
        precondition(!idle.consumeOpening(at: 45, startAngle: 90), "locking without sleep must not animate")

        var cancelled = WakeState()
        cancelled.pause(.locked, wasClosing: true)
        cancelled.cancelOpening()
        cancelled.pause(.systemSleep, wasClosing: false)
        cancelled.resume(.locked)
        cancelled.resume(.systemSleep)
        precondition(!cancelled.consumeOpening(at: 45, startAngle: 90), "disabling or cancelling must clear the pending opening")

        var alreadyOpen = WakeState()
        alreadyOpen.pause(.displaySleep, wasClosing: true)
        alreadyOpen.resume(.displaySleep)
        precondition(!alreadyOpen.consumeOpening(at: 104, startAngle: 90), "do not replay an opening after the lid is already open")
        precondition(!alreadyOpen.consumeOpening(at: 45, startAngle: 90), "a skipped wake must not trigger on a later close")
        print("wake state passed: sleep and lock ordering, active session, cancellation, no delayed replay")
    }
}
