@main
struct WakeStateTests {
    static func main() {
        var lockedFirst = WakeState()
        lockedFirst.pause(.locked, wasClosing: true)
        precondition(!lockedFirst.isSuspended, "lock alone must allow angle tracking")
        lockedFirst.pause(.systemSleep, wasClosing: true)
        lockedFirst.pause(.displaySleep, wasClosing: false)
        lockedFirst.resume(.systemSleep)
        lockedFirst.resume(.displaySleep)
        precondition(!lockedFirst.isSuspended && lockedFirst.needsOpening(at: 45, startAngle: 90), "reopening must start on the lock screen after wake")
        precondition(lockedFirst.needsOpening(at: 48, startAngle: 90), "a display change during capture must preserve opening until the first frame")
        lockedFirst.openingStarted()
        lockedFirst.resume(.locked)
        precondition(!lockedFirst.needsOpening(at: 45, startAngle: 90), "unlock must not replay the opening")
        lockedFirst.resume(.systemSleep)
        lockedFirst.resume(.displaySleep)
        precondition(!lockedFirst.needsOpening(at: 45, startAngle: 90), "duplicate wake must not replay the opening")

        var sleepingFirst = WakeState()
        sleepingFirst.pause(.systemSleep, wasClosing: true)
        sleepingFirst.pause(.displaySleep, wasClosing: false)
        sleepingFirst.pause(.locked, wasClosing: false)
        sleepingFirst.resume(.locked)
        sleepingFirst.resume(.systemSleep)
        precondition(!sleepingFirst.needsOpening(at: 45, startAngle: 90), "unlock must wait for the display to wake")
        sleepingFirst.pause(.inactiveSession, wasClosing: false)
        sleepingFirst.resume(.displaySleep)
        precondition(!sleepingFirst.needsOpening(at: 45, startAngle: 90), "opening must stay hidden in another user's session")
        sleepingFirst.resume(.inactiveSession)
        precondition(sleepingFirst.needsOpening(at: 45, startAngle: 90), "active unlocked desktop must receive one opening")

        var idle = WakeState()
        idle.pause(.systemSleep, wasClosing: false)
        idle.resume(.systemSleep)
        precondition(!idle.needsOpening(at: 45, startAngle: 90), "idle sleep with an open lid must not animate")
        idle.pause(.locked, wasClosing: true)
        idle.resume(.locked)
        precondition(!idle.needsOpening(at: 45, startAngle: 90), "locking without sleep must not animate")

        var alreadyLocked = WakeState()
        alreadyLocked.pause(.locked, wasClosing: false)
        alreadyLocked.pause(.displaySleep, wasClosing: true)
        alreadyLocked.resume(.displaySleep)
        precondition(alreadyLocked.needsOpening(at: 45, startAngle: 90), "closing after manual lock must preserve opening")

        var cancelled = WakeState()
        cancelled.pause(.locked, wasClosing: true)
        cancelled.cancelOpening()
        cancelled.pause(.systemSleep, wasClosing: false)
        cancelled.resume(.locked)
        cancelled.resume(.systemSleep)
        precondition(!cancelled.needsOpening(at: 45, startAngle: 90), "disabling or cancelling must clear the pending opening")

        var alreadyOpen = WakeState()
        alreadyOpen.pause(.displaySleep, wasClosing: true)
        alreadyOpen.resume(.displaySleep)
        precondition(!alreadyOpen.needsOpening(at: 104, startAngle: 90), "do not replay an opening after the lid is already open")
        precondition(!alreadyOpen.needsOpening(at: 45, startAngle: 90), "a skipped wake must not trigger on a later close")
        print("wake state passed: sleep and lock ordering, active session, cancellation, no delayed replay")
    }
}
